language: java
bundler_args: --retry 1
os: linux
sudo: false

install: true

script:
  - mvn clean verify

cache:
  directories:
  - $HOME/.m2/repository

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

deploy:
  provider: releases
  api_key:
    secure: "SMpUQqvbR8ZFfe4wYDncLjnsIpDEDqVidqbQk4cSALGivfOTGn96yVhGzDTiaynnDzGihY972ulyxJis3Jwsk4u/qHur5auWjINxnPXJILAbSOi5iYh+oZ6gdKxPLK+OQlnEAJqEsXW1GT7059GAvF+2Zp3xYKmTCjHT32sg3aL6pOjM6DjpAwkIYoLYhaB4yuBBRhyxU2e1lqAYaDcwCHWGzQRlSSVD9BFKGgNUOE9dw9QF6RkxRfKGFv8xnO8WQpVu6/pkLbJna4R+Eqa1kE2rNNkfuVvF5xz2VcdE9hWGRKgdhu90mgqSMmcGD3UVQiS1BDpZw7yKRBLDHD5IpCKlSmzPlikDJakroJj++KQhtF3RjxUU8PqWQyH8w64iwTCdZpNICiR1EVV4T4XH1cZKc/y3byjorsy0UtgL+Rcktbb9UrQMOBrcuu1LJQ1I3445n4AA/aCoVR6JpfA4DzM0H7lOH7zsoybUSPwb6HrvYDc4yQqp8CFtUXTHgF6wHWeibs41Oa46ARC8O8oDtwmFVnIktVh1zm6DqUtaNujGcR1zi6pZqeHWYIAy1fMe7pwNrauTf621FDMTBwl1P+hOs2DBCBcFoKtZvB3d0tt7JKleyr0Lq1qQVP4juEpUYI1c+OPKUtoWIQumt14nHMoYNq5Fgb4L58B9Xlrgeyk="
  file: "target/apt-cli.jar"
  skip_cleanup: true
  on:
    tags: true